# Generated by Django 6.0 on 2026-03-05 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_customuser_managers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('SUPER_TEACHER', 'Super Teacher'), ('TEACHER', 'Teacher'), ('STUDENT', 'Student')], max_length=50),
        ),
    ]
